# Site settings
title: MGSX
email: info@mgsx.net
description: > # this means to ignore newlines until "baseurl:"
  MGSX Network, software, games, digital art.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mgsx.net" # the base hostname & protocol for your site
twitter_username: 
github_username:  mgsx-dev
bitbucket_username: germ1

